version: "3"
services:
  mongo:
    build:
      context: ./mongo
      dockerfile: Dockerfile
    volumes:
      - ./mongo/data:/data/db
      - ./mongo/init/:docker-entrypoint-initdb.d/
    environment:
      - MONGO_INITDB_DATANASE=ballots
  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - "4160"
      - "4161"
  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - "4150"
      - "4151"
  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd  
    ports:
      - "4171"
